In [1]:
import numpy as np
import pandas as pd
import glob
import sys

# loading some functions we wrote before
sys.path.append("/Users/jonathanramos/Desktop/LRI/Image ROI Data Wrangling/")
from clean import *
from norm import *
from count import *

In [15]:
df_ram8 = pd.read_csv('RAM-8_raw_data.csv')
print(df_ram8.columns)
print(df_ram8.shape)
df_ram8.head()

Index(['Unnamed: 0', ' ', 'AR', 'AnalysisDate', 'Area', 'Background',
       'CellNumber', 'Circ.', 'Experiment', 'FileName', 'Ind_var_group',
       'Indi_var_group', 'Integrated_Density', 'Max', 'Mean',
       'Mean-Background', 'Min', 'Round', 'Solidity', 'Stain', 'StdDev',
       'Subject', 'XM', 'YM', 'directory', 'roiName', 'Rat_n', 'Coord', 'Sex',
       'Dox', 'React'],
      dtype='object')
(12670, 31)

,Unnamed: 0,,AR,AnalysisDate,Area,Background,CellNumber,Circ.,Experiment,FileName,...,Subject,XM,YM,directory,roiName,Rat_n,Coord,Sex,Dox,React
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,10.0,345.615,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,10.0,57.237,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,10.0,13.054,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,rat10C,"(13.054, 117.141)",F,DOX_ON,FR1
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,10.0,368.777,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,rat10C,"(368.777, 231.472)",F,DOX_ON,FR1
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,10.0,107.768,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1

In [16]:
df_ram9 = pd.read_csv('RAM-9_raw_data.csv')
print(df_ram9.columns)
print(df_ram9.shape)
df_ram9.head()

Index(['Unnamed: 0', ' ', 'AR', 'AnalysisDate', 'Area', 'Background',
       'CellNumber', 'Circ.', 'Experiment', 'FileName', 'Ind_var_group',
       'Indi_var_group', 'Integrated_Density', 'Max', 'Mean',
       'Mean-Background', 'Min', 'Round', 'Solidity', 'Stain', 'StdDev',
       'Subject', 'XM', 'YM', 'directory', 'roiName', 'Rat_n', 'Treatment',
       'Coord', 'Sex', 'Dox', 'React'],
      dtype='object')
(18185, 32)

/var/folders/b2/3h2lpxx14kgb12pp_7pltxnc0000gn/T/ipykernel_27888/2915602767.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ram9 = pd.read_csv('RAM-9_raw_data.csv')

,Unnamed: 0,,AR,AnalysisDate,Area,Background,CellNumber,Circ.,Experiment,FileName,...,XM,YM,directory,roiName,Rat_n,Treatment,Coord,Sex,Dox,React
0,0,1,1.600,_5_18_2022_at_17-23,72.950,40.333,1,0.612,RAM-9,RAM-9_11B_A_1,...,79.999,85.187,data/RAM-9_11B_A_1/RAM-9_11B_A_1_{single}_{c-F...,0102b-0095,rat_11B,OFF-DOX,"(79.999, 85.18700000000001)",F,DOX_OFF,FR1
1,1,2,1.000,_5_18_2022_at_17-23,39.982,40.333,2,0.504,RAM-9,RAM-9_11B_A_1,...,55.931,167.410,data/RAM-9_11B_A_1/RAM-9_11B_A_1_{single}_{c-F...,0201b-0066,rat_11B,OFF-DOX,"(55.931000000000004, 167.41)",F,DOX_OFF,FR1
2,2,3,1.171,_5_18_2022_at_17-23,33.669,40.333,3,0.311,RAM-9,RAM-9_11B_A_1,...,314.323,195.588,data/RAM-9_11B_A_1/RAM-9_11B_A_1_{single}_{c-F...,0234b-0375,rat_11B,OFF-DOX,"(314.323, 195.588)",F,DOX_OFF,FR1
3,3,4,1.287,_5_18_2022_at_17-23,65.935,40.333,4,0.760,RAM-9,RAM-9_11B_A_1,...,254.726,164.704,data/RAM-9_11B_A_1/RAM-9_11B_A_1_{single}_{c-F...,0198b-0304,rat_11B,OFF-DOX,"(254.726, 164.704)",F,DOX_OFF,FR1
4,4,5,1.092,_5_18_2022_at_17-23,46.295,40.333,5,0.930,RAM-9,RAM-9_11B_A_1,...,176.981,149.560,data/RAM-9_11B_A_1/RAM-9_11B_A_1_{single}_{c-F...,0179b-0211,rat_11B,OFF-DOX,"(176.981, 149.56)",F,DOX_OFF,FR1

In [17]:
df = pd.concat([df_ram8, df_ram9])
print(df.columns)
print(df.shape)
df.head()

Index(['Unnamed: 0', ' ', 'AR', 'AnalysisDate', 'Area', 'Background',
       'CellNumber', 'Circ.', 'Experiment', 'FileName', 'Ind_var_group',
       'Indi_var_group', 'Integrated_Density', 'Max', 'Mean',
       'Mean-Background', 'Min', 'Round', 'Solidity', 'Stain', 'StdDev',
       'Subject', 'XM', 'YM', 'directory', 'roiName', 'Rat_n', 'Coord', 'Sex',
       'Dox', 'React', 'Treatment'],
      dtype='object')
(30855, 32)

,Unnamed: 0,,AR,AnalysisDate,Area,Background,CellNumber,Circ.,Experiment,FileName,...,XM,YM,directory,roiName,Rat_n,Coord,Sex,Dox,React,Treatment
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,345.615,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,NaN
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,57.237,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,NaN
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,13.054,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,NaN
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,368.777,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,NaN
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,107.768,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,NaN

In [44]:
df.columns = [col.lower() for col in df.columns]
df['treatment'] = df[['dox', 'react']].aggregate('_'.join, axis=1)
df['image_name'] = df.filename.apply(lambda x: '_'.join(x.split('_')[:-1]))
df['image_name'] = df[['rat_n', 'image_name']].aggregate('_'.join, axis=1)
df

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,ym,directory,roiname,rat_n,coord,sex,dox,react,treatment,image_name
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18180,3,4,1.171,_5_18_2022_at_16-56,48.399,5.675,4.0,0.447,RAM-9,RAM-9_7B_D_3,...,207.464,data/RAM-9_7B_D_3/RAM-9_7B_D_3_{single}_{DAPI}...,0247c-0310,RAM-9_rat_7B,"(260.259, 207.46400000000003)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-9_rat_7B_RAM-9_7B_D
18181,4,5,1.000,_5_18_2022_at_16-56,46.997,5.675,5.0,0.333,RAM-9,RAM-9_7B_D_3,...,195.296,data/RAM-9_7B_D_3/RAM-9_7B_D_3_{single}_{DAPI}...,0232c-0231,RAM-9_rat_7B,"(193.55700000000002, 195.296)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-9_rat_7B_RAM-9_7B_D
18182,0,1,1.188,_5_18_2022_at_16-56,46.295,5.675,1.0,0.836,RAM-9,RAM-9_7B_D_3.tif,...,84.184,data/double-label_results/RAM-9_7B_D_3_{double...,0099c-0413,RAM-9_rat_7B,"(347.029, 84.184)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-9_rat_7B_RAM-9_7B_D
18183,1,2,1.171,_5_18_2022_at_16-56,48.399,5.675,2.0,0.447,RAM-9,RAM-9_7B_D_3.tif,...,207.464,data/double-label_results/RAM-9_7B_D_3_{double...,0247c-0310,RAM-9_rat_7B,"(260.259, 207.46400000000003)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-9_rat_7B_RAM-9_7B_D
18184,0,1,1.097,_5_18_2022_at_16-56,56.817,5.675,1.0,0.490,RAM-9,RAM-9_7B_D_3.tif,...,157.231,data/double-label_results/RAM-9_7B_D_3_{double...,0188c-0481,RAM-9_rat_7B,"(401.149, 157.231)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-9_rat_7B_RAM-9_7B_D

In [19]:
df['rat_n'] = df.rat_n.apply(lambda x: 'RAM-8_'+x if 'C' in x else 'RAM-9_'+x)
df

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,xm,ym,directory,roiname,rat_n,coord,sex,dox,react,treatment
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,345.615,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,57.237,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,13.054,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,368.777,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,107.768,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18180,3,4,1.171,_5_18_2022_at_16-56,48.399,5.675,4.0,0.447,RAM-9,RAM-9_7B_D_3,...,260.259,207.464,data/RAM-9_7B_D_3/RAM-9_7B_D_3_{single}_{DAPI}...,0247c-0310,RAM-9_rat_7B,"(260.259, 207.46400000000003)",F,DOX_ON,FR1,DOX_ON_FR1
18181,4,5,1.000,_5_18_2022_at_16-56,46.997,5.675,5.0,0.333,RAM-9,RAM-9_7B_D_3,...,193.557,195.296,data/RAM-9_7B_D_3/RAM-9_7B_D_3_{single}_{DAPI}...,0232c-0231,RAM-9_rat_7B,"(193.55700000000002, 195.296)",F,DOX_ON,FR1,DOX_ON_FR1
18182,0,1,1.188,_5_18_2022_at_16-56,46.295,5.675,1.0,0.836,RAM-9,RAM-9_7B_D_3.tif,...,347.029,84.184,data/double-label_results/RAM-9_7B_D_3_{double...,0099c-0413,RAM-9_rat_7B,"(347.029, 84.184)",F,DOX_ON,FR1,DOX_ON_FR1
18183,1,2,1.171,_5_18_2022_at_16-56,48.399,5.675,2.0,0.447,RAM-9,RAM-9_7B_D_3.tif,...,260.259,207.464,data/double-label_results/RAM-9_7B_D_3_{double...,0247c-0310,RAM-9_rat_7B,"(260.259, 207.46400000000003)",F,DOX_ON,FR1,DOX_ON_FR1
18184,0,1,1.097,_5_18_2022_at_16-56,56.817,5.675,1.0,0.490,RAM-9,RAM-9_7B_D_3.tif,...,401.149,157.231,data/double-label_results/RAM-9_7B_D_3_{double...,0188c-0481,RAM-9_rat_7B,"(401.149, 157.231)",F,DOX_ON,FR1,DOX_ON_FR1

# check for duplicates, nulls

In [25]:
subset = [x.lower() for x in ['XM', 'YM', 'directory', 'roiName', 'FileName', 'Mean']]
df = df.drop_duplicates(subset=subset).copy()
print(df.duplicated(subset=subset).sum())
print(df.shape)
df.head()

0
(30656, 32)

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,xm,ym,directory,roiname,rat_n,coord,sex,dox,react,treatment
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,345.615,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,57.237,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,13.054,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,368.777,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,107.768,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1

In [26]:
# build cols we still need
df['mean-background'] = df['mean'] - df['background']
df.head()

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,xm,ym,directory,roiname,rat_n,coord,sex,dox,react,treatment
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,345.615,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,57.237,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,13.054,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,368.777,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,107.768,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1

### standardizing stain labels

In [38]:
df['stain'] = df.stain.apply(lambda x: x.replace('c-Fos', 'cFos')\
    .replace('with', 'w')\
    .replace('/','')\
    .replace('GFP','EGFP')\
    .replace('EEGFP', 'EGFP')\
    .replace('Triple-labeled', 'triple')\
    .replace('single_',''))

print(np.unique(df.stain))

['EGFP' 'EGFP_coloc_w_cFos' 'EGFP_coloc_w_mKate2' 'cFos'
 'cFos_coloc_w_EGFP' 'cFos_coloc_w_mKate2' 'mKate2' 'mKate2_coloc_w_EGFP'
 'mKate2_coloc_w_cFos' 'triple_EGFP' 'triple_cFos' 'triple_mKate2']

In [52]:
print(df.shape)
df = df[df.rat_n != 'RAM-8_rat7C']
print(df.shape)
df.head()

(30656, 33)
(30365, 33)

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,ym,directory,roiname,rat_n,coord,sex,dox,react,treatment,image_name
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,79.261,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,77.429,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,117.141,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,231.472,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,29.112,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A

In [53]:
cFos_min = abs(df[df.stain.str.contains('cFos')]['mean-background'].min())
mKate_min = abs(df[df.stain.str.contains('mKate2')]['mean-background'].min())
EGFP_min = abs(df[df.stain.str.contains('EGFP')]['mean-background'].min())

print(cFos_min)
print(mKate_min)
print(EGFP_min)

def adjust_intensity(x):
    if 'cFos' in x.stain:
        return x['mean-background'] + cFos_min
    elif 'mKate2' in x.stain:
        return x['mean-background'] + mKate_min
    elif 'EGFP' in x.stain:
        return x['mean-background'] + EGFP_min
    else:
        print('missing val')
        return np.nan

df_adjusted = df.copy(deep=True)
df_adjusted['mean-background'] = df.apply(adjust_intensity, axis=1)

0.32999999999999985
0.22999999999999998
0.8579999999999997

In [54]:
print(df['mean-background'][:5])
print(df_adjusted['mean-background'][:5])

0     84.240
1     83.398
2    198.139
3     35.092
4    138.015
Name: mean-background, dtype: float64
0     84.570
1     83.728
2    198.469
3     35.422
4    138.345
Name: mean-background, dtype: float64

In [39]:
df.treatment.unique()

array(['DOX_ON_FR1', 'DOX_OFF_VR5', 'DOX_OFF_FR1', 'DOX_OFF_NR',
       'DOX_ON_VR5'], dtype=object)

# Normalizing Intensity to OFF_DOX FR1

In [55]:
for stain in df_adjusted.stain.unique():
    print(stain)
    df_q = df_adjusted.query(f'stain == "{stain}"').copy()
    norm_condition = 'DOX_OFF_FR1'
    df_norm_condition = df_q.query(f'treatment == "{norm_condition}"')
    norm_mean = df_norm_condition['mean-background'].mean()
    df_q['norm_mean-background'] = df_q['mean-background'] / norm_mean
    print(df_q.groupby('treatment')['norm_mean-background'].mean(),'\n')

    s = stain.replace('/','').replace('-','')

    prism_reorg(df_q).to_csv(f'RAM-8,9_norm_{s}_PRISM.csv')

cFos
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     1.292833
DOX_OFF_VR5    1.201544
DOX_ON_FR1     1.143156
DOX_ON_VR5     1.060619
Name: norm_mean-background, dtype: float64

EGFP
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.464677
DOX_OFF_VR5    1.335270
DOX_ON_FR1     0.999749
DOX_ON_VR5     0.603055
Name: norm_mean-background, dtype: float64

mKate2
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.947470
DOX_OFF_VR5    0.975826
DOX_ON_FR1     0.040257
DOX_ON_VR5     0.020239
Name: norm_mean-background, dtype: float64

cFos_coloc_w_EGFP
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.960882
DOX_OFF_VR5    1.207284
DOX_ON_FR1     1.215441
DOX_ON_VR5     0.749528
Name: norm_mean-background, dtype: float64

EGFP_coloc_w_cFos
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.509544
DOX_OFF_VR5    1.308891
DOX_ON_FR1     0.931081
DOX_ON_VR5     0.690790
Name: norm_mean-background, dtype: float64

mKate2_coloc_w_EGFP
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.931556
DOX_OFF_VR5    0.981051
DOX_ON_FR1     0.037641
DOX_ON_VR5     0.031906
Name: norm_mean-background, dtype: float64

cFos_coloc_w_mKate2
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     1.477675
DOX_OFF_VR5    1.102688
DOX_ON_FR1     1.359629
Name: norm_mean-background, dtype: float64

mKate2_coloc_w_cFos
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.853331
DOX_OFF_VR5    1.127346
DOX_ON_FR1     0.036181
Name: norm_mean-background, dtype: float64

triple_cFos
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.587529
DOX_OFF_VR5    1.052385
DOX_ON_FR1     1.892191
Name: norm_mean-background, dtype: float64

triple_EGFP
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.511069
DOX_OFF_VR5    1.092277
DOX_ON_FR1     1.054898
Name: norm_mean-background, dtype: float64

triple_mKate2
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_NR     0.969598
DOX_OFF_VR5    1.311472
DOX_ON_FR1     0.032006
Name: norm_mean-background, dtype: float64

EGFP_coloc_w_mKate2
treatment
DOX_OFF_FR1    1.000000
DOX_OFF_VR5    1.316715
DOX_ON_FR1     1.153137
Name: norm_mean-background, dtype: float64

# Counting Mean Cell ns

In [61]:
df_img_ns = df.groupby('rat_n')['image_name'].unique().reset_index()
df_img_ns['n_imgs'] = df_img_ns.image_name.apply(len)
df_img_ns

            rat_n                                         image_name  n_imgs
0    RAM-8_rat10C  [RAM-8_rat10C_3.4_PL_A, RAM-8_rat10C_3.9_PL_A,...       3
1    RAM-8_rat12C  [RAM-8_rat12C_3.1_PL_A, RAM-8_rat12C_3.1_PL_B,...       5
2    RAM-8_rat13C  [RAM-8_rat13C_3.1_PL_A, RAM-8_rat13C_3.2_PL_A,...       5
3    RAM-8_rat15C  [RAM-8_rat15C_3.2_PL_A, RAM-8_rat15C_3.2_PL_B,...       6
4    RAM-8_rat16C  [RAM-8_rat16C_3.1_PL_A, RAM-8_rat16C_3.6_PL_A,...       4
5     RAM-8_rat1C  [RAM-8_rat1C_2.9_PL_A, RAM-8_rat1C_3.0_PL_A, R...       6
6     RAM-8_rat3C  [RAM-8_rat3C_3.6_PL_A, RAM-8_rat3C_4.0_PL_A, R...       3
7     RAM-8_rat4C  [RAM-8_rat4C_3.0_PL_A, RAM-8_rat4C_3.2_PL_A, R...       3
8     RAM-8_rat5C  [RAM-8_rat5C_3.0_PL_A, RAM-8_rat5C_3.3_PL_A, R...       5
9     RAM-8_rat8C  [RAM-8_rat8C_3.2_PL_A, RAM-8_rat8C_3.4_PL_A, R...       3
10  RAM-9_rat_11B  [RAM-9_rat_11B_RAM-9_11B_A, RAM-9_rat_11B_RAM-...       3
11  RAM-9_rat_12B  [RAM-9_rat_12B_RAM-9_12B_C, RAM-9_rat_12B_RAM-...       4
12  RAM-9_rat_14B  [RAM-9_rat_14B_RAM-9_14B_A, RAM-9_rat_14B_RAM-...       4
13   RAM-9_rat_1B  [RAM-9_rat_1B_RAM-9_1B_A, RAM-9_rat_1B_RAM-9_1...       4
14   RAM-9_rat_2B  [RAM-9_rat_2B_RAM-9_2B_A, RAM-9_rat_2B_RAM-9_2...       4
15   RAM-9_rat_3B  [RAM-9_rat_3B_RAM-9_3B_A, RAM-9_rat_3B_RAM-9_3...       4
16   RAM-9_rat_5B  [RAM-9_rat_5B_RAM-9_5B_A, RAM-9_rat_5B_RAM-9_5...       4
17   RAM-9_rat_7B  [RAM-9_rat_7B_RAM-9_7B_A, RAM-9_rat_7B_RAM-9_7...       4

### All stain-type combinations

In [133]:
def mean_cell_ns_single(stain_x):
    # series of groupby's and reductions to get sum of sums per rat
    # first groupby to count cells per image; second groupby to sum counts per rat
    # merge with df to get required labels, merge with df_img_ns to get n_imgs per rat
    q = df_adjusted.query(f'stain == "{stain_x}"')\
        .groupby('image_name')['rat_n'].count()\
        .reset_index().rename(columns={'rat_n':'count'})\
        .merge(df_adjusted[['image_name', 'rat_n']], on='image_name', how='left')\
        .drop_duplicates()\
        .groupby('rat_n')['count'].sum().reset_index().rename(columns={'count':'sum'})\
        .merge(df_adjusted[['rat_n', 'react', 'dox']],\
            on='rat_n', how='left')\
        .drop_duplicates().reset_index()\
        .merge(df_img_ns[['rat_n', 'n_imgs']], on='rat_n', how='left')

    # compute means
    q['mean_cell_n'] = q['sum'] / q['n_imgs']

    # sort by dox then react; reorder cols
    q = q.sort_values(by=['dox', 'react'])\
        [['rat_n', 'dox', 'react', 'sum', 'n_imgs', 'mean_cell_n']]\
        .reset_index().drop('index', axis=1)

    return q

df_total_cFos = mean_cell_ns_single('cFos')

# these should be identical, but i'm performing both queries for completeness
mean_cell_ns_single('cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_mean_cell_ns.csv')
mean_cell_ns_single('mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_mKate_mean_cell_ns.csv')
mean_cell_ns_single('EGFP').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_EGFP_mean_cell_ns.csv')

mean_cell_ns_single('cFos_coloc_w_mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_coloc_w_mKate2_mean_cell_ns.csv')
mean_cell_ns_single('cFos_coloc_w_EGFP').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_coloc_w_EGFP_mean_cell_ns.csv')
mean_cell_ns_single('mKate2_coloc_w_cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_mKate2_coloc_w_cFos_mean_cell_ns.csv')
mean_cell_ns_single('mKate2_coloc_w_EGFP').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_mKate2_coloc_w_EGFP_mean_cell_ns.csv')
mean_cell_ns_single('EGFP_coloc_w_cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_EGFP_coloc_w_cFos_mean_cell_ns.csv')
mean_cell_ns_single('EGFP_coloc_w_mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_EGFP_coloc_w_mKate2_mean_cell_ns.csv')

mean_cell_ns_single('triple_cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_triple_cFos_mean_cell_ns.csv')
mean_cell_ns_single('triple_mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_triple_mKate2_mean_cell_ns.csv')
mean_cell_ns_single('triple_EGFP').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_triple_EGFP_mean_cell_ns.csv')

### percent overlap

In [134]:
# since I only have to do this a few times i'll just be lazy and type it all out
# instead of parameterizing

df_total_cFos = mean_cell_ns_single('cFos')
df_total_mKate = mean_cell_ns_single('mKate2')

df_cFos_w_mKate = mean_cell_ns_single('cFos_coloc_w_mKate2')
df_mKate_w_cFos = mean_cell_ns_single('mKate2_coloc_w_cFos')

df_total_cFos['total_cFos'] = df_total_cFos['sum']
df_total_mKate['total_mKate'] = df_total_mKate['sum']

df_cFos_w_mKate['total_cFos_coloc_w_mKate'] = df_cFos_w_mKate['sum']
df_mKate_w_cFos['total_mKate_coloc_w_cFos'] = df_mKate_w_cFos['sum']

df_percent_cFos_w_mKate = df_cFos_w_mKate[['rat_n', 'dox', 'react', 'total_cFos_coloc_w_mKate']].merge(df_total_cFos[['rat_n', 'dox', 'react', 'total_cFos']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_cFos_w_mKate['percent'] = df_percent_cFos_w_mKate.total_cFos_coloc_w_mKate / df_percent_cFos_w_mKate.total_cFos * 100
df_percent_cFos_w_mKate.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_cFos_percent_mKate_overlap.csv')

df_percent_mKate_w_cFos = df_mKate_w_cFos[['rat_n', 'dox', 'react', 'total_mKate_coloc_w_cFos']].merge(df_total_mKate[['rat_n', 'dox', 'react', 'total_mKate']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_mKate_w_cFos['percent'] = df_percent_mKate_w_cFos.total_mKate_coloc_w_cFos / df_percent_mKate_w_cFos.total_mKate * 100
df_percent_mKate_w_cFos.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_mKate_percent_cFos_overlap.csv')

# splitting hi/lo cFos

In [103]:
cFos_stains = set(['cFos', 'cFos_coloc_w_mKate2', 'cFos_coloc_w_EGFP', 'triple_cFos'])
df_cFos = df_adjusted[df_adjusted.stain.apply(lambda x: x in cFos_stains)].copy(deep=True)
cFos_median = df_cFos['mean-background'].median()
df_cFos['cFos_split'] = df_cFos['mean-background'].apply(lambda x: 'cFos_hi' if x > cFos_median else 'cFos_lo')

print(df_cFos.shape)
print(df_cFos.stain.unique())
df_cFos.head()

(8226, 34)
['cFos' 'cFos_coloc_w_EGFP' 'cFos_coloc_w_mKate2' 'triple_cFos']

,unnamed: 0,,ar,analysisdate,area,background,cellnumber,circ.,experiment,filename,...,directory,roiname,rat_n,coord,sex,dox,react,treatment,image_name,cFos_split
0,0,1,1.092,_5_3_2021_at_8-34,43.489,56.949,1.0,0.873,RAM008,3.4_PL_A_2,...,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00002,RAM-8_rat10C,"(345.615, 79.26100000000001)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A,cFos_hi
1,1,2,1.000,_5_3_2021_at_8-34,64.533,56.949,2.0,0.968,RAM008,3.4_PL_A_2,...,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00010,RAM-8_rat10C,"(57.236999999999995, 77.429)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A,cFos_hi
2,2,3,1.169,_5_3_2021_at_8-34,66.637,56.949,3.0,0.996,RAM008,3.4_PL_A_2,...,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00007,RAM-8_rat10C,"(13.054, 117.141)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A,cFos_hi
3,3,4,1.302,_5_3_2021_at_8-34,25.252,56.949,4.0,0.562,RAM008,3.4_PL_A_2,...,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00003,RAM-8_rat10C,"(368.777, 231.472)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A,cFos_lo
4,4,5,1.083,_5_3_2021_at_8-34,59.623,56.949,5.0,0.981,RAM008,3.4_PL_A_2,...,/Volumes/T7/RAM008_Images/RAM008_10C_cfos405_e...,005-00009,RAM-8_rat10C,"(107.76799999999999, 29.112)",F,DOX_ON,FR1,DOX_ON_FR1,RAM-8_rat10C_3.4_PL_A,cFos_hi

In [137]:
def mean_cell_ns_cFosSplit(cFos_split, stain_x):
    # series of groupby's and reductions to get sum of sums per rat
    # first groupby to count cells per image; second groupby to sum counts per rat
    # merge with df to get required labels, merge with df_img_ns to get n_imgs per rat
    q = df_cFos.query(f'cFos_split == "{cFos_split}" and stain == "{stain_x}"')\
        .groupby('image_name')['rat_n'].count()\
        .reset_index().rename(columns={'rat_n':'count'})\
        .merge(df_cFos[['image_name', 'rat_n']], on='image_name', how='left')\
        .drop_duplicates()\
        .groupby('rat_n')['count'].sum().reset_index().rename(columns={'count':'sum'})\
        .merge(df_cFos[['rat_n', 'react', 'dox']],\
            on='rat_n', how='left')\
        .drop_duplicates().reset_index()\
        .merge(df_img_ns[['rat_n', 'n_imgs']], on='rat_n', how='left')

    # compute means
    q['mean_cell_n'] = q['sum'] / q['n_imgs']

    # sort by dox then react; reorder cols
    q = q.sort_values(by=['dox', 'react'])\
        [['rat_n', 'dox', 'react', 'sum', 'n_imgs', 'mean_cell_n']]\
        .reset_index().drop('index', axis=1)

    return q

mean_cell_ns_cFosSplit('cFos_hi', 'cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_hi_mean_cell_ns.csv')
mean_cell_ns_cFosSplit('cFos_lo', 'cFos').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_lo_mean_cell_ns.csv')

mean_cell_ns_cFosSplit('cFos_hi', 'cFos_coloc_w_mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_hi_coloc_w_mKate2_mean_cell_ns.csv')
mean_cell_ns_cFosSplit('cFos_lo', 'cFos_coloc_w_mKate2').merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_cFos_lo_coloc_w_mKate2_mean_cell_ns.csv')

In [135]:
df_cFos_hi = mean_cell_ns_cFosSplit('cFos_hi', 'cFos')
df_cFos_lo = mean_cell_ns_cFosSplit('cFos_lo', 'cFos')

df_cFos_hi_w_mKate = mean_cell_ns_cFosSplit('cFos_hi', 'cFos_coloc_w_mKate2')
df_cFos_lo_w_mKate = mean_cell_ns_cFosSplit('cFos_lo', 'cFos_coloc_w_mKate2')

df_cFos_hi['total_cFos_hi'] = df_cFos_hi['sum']
df_cFos_lo['total_cFos_lo'] = df_cFos_lo['sum']

df_cFos_hi_w_mKate['total_cFos_hi_coloc_w_mKate'] = df_cFos_hi_w_mKate['sum']
df_cFos_lo_w_mKate['total_cFos_lo_coloc_w_mKate'] = df_cFos_lo_w_mKate['sum']

df_percent_cFos_hi_w_mKate = df_cFos_hi_w_mKate[['rat_n', 'dox', 'react', 'total_cFos_hi_coloc_w_mKate']].merge(df_cFos_hi[['rat_n', 'dox', 'react', 'total_cFos_hi']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_cFos_hi_w_mKate['percent'] = df_percent_cFos_hi_w_mKate.total_cFos_hi_coloc_w_mKate / df_percent_cFos_hi_w_mKate.total_cFos_hi * 100
df_percent_cFos_hi_w_mKate.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_cFos_hi_percent_mKate_overlap.csv')

df_percent_cFos_lo_w_mKate = df_cFos_lo_w_mKate[['rat_n', 'dox', 'react', 'total_cFos_lo_coloc_w_mKate']].merge(df_cFos_lo[['rat_n', 'dox', 'react', 'total_cFos_lo']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_cFos_lo_w_mKate['percent'] = df_percent_cFos_lo_w_mKate.total_cFos_lo_coloc_w_mKate / df_percent_cFos_lo_w_mKate.total_cFos_lo * 100
df_percent_cFos_lo_w_mKate.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_cFos_lo_percent_mKate_overlap.csv')

In [141]:
df_cFos_hi_w_mKate['total_mKate_coloc_w_cFos_hi'] = df_cFos_hi_w_mKate['sum']
df_cFos_lo_w_mKate['total_mKate_coloc_w_cFos_lo'] = df_cFos_lo_w_mKate['sum']
df_mKate_w_cFos_hi = df_cFos_hi_w_mKate.drop('total_cFos_hi_coloc_w_mKate',axis=1).copy(deep=True)
df_mKate_w_cFos_lo = df_cFos_lo_w_mKate.drop('total_cFos_lo_coloc_w_mKate',axis=1).copy(deep=True)

df_percent_mKate_w_cFos_hi = df_mKate_w_cFos_hi[['rat_n', 'dox', 'react', 'total_mKate_coloc_w_cFos_hi']].merge(df_total_mKate[['rat_n', 'dox', 'react', 'total_mKate']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_mKate_w_cFos_hi['percent'] = df_percent_mKate_w_cFos_hi.total_mKate_coloc_w_cFos_hi / df_percent_mKate_w_cFos_hi.total_mKate * 100
df_percent_mKate_w_cFos_hi.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_mKate_percent_cFos_hi_overlap.csv')

df_percent_mKate_w_cFos_lo = df_mKate_w_cFos_lo[['rat_n', 'dox', 'react', 'total_mKate_coloc_w_cFos_lo']].merge(df_total_mKate[['rat_n', 'dox', 'react', 'total_mKate']], on=['rat_n', 'dox', 'react'], how='left')
df_percent_mKate_w_cFos_lo['percent'] = df_percent_mKate_w_cFos_lo.total_mKate_coloc_w_cFos_lo / df_percent_mKate_w_cFos_lo.total_mKate * 100
df_percent_mKate_w_cFos_lo.merge(df_total_cFos[['rat_n', 'dox', 'react']], on=['rat_n','dox', 'react'], how='right').to_csv('RAM-8,9_TOTAL_mKate_percent_cFos_lo_overlap.csv')